language: ruby
rvm:
- 2.1.1
install:
- gem install sass --version 3.2.19
- gem install jekyll
- gem install jekyll-sitemap
- gem install s3_website
- gem install compass --version 0.12.5
- gem install kramdown
- gem install link-checker
before_script:
- cd site
script:
- jekyll build
after_success:
- s3_website push
- check-links 'http://www.lifelinter.com'
- cd ..
env:
  global:
  - secure: cB2hODqR9V3P8c2BupySJnz825snT2vqhpB4RnnyYD5L1E+nzZK9KdApgx0U/f1YHZujhPnbdXAfq1QQztIf6EocbF1CrSKPCavJoJ/CSQ53X775++PegBZXL66PSYfMX28MFcuYCvqcBxSKX26kpT72IjtgHHEROz/NkrifHog=
  - secure: Ri3M0/J5J11LpMSSD3XoJdB/rkINP3Ir9leoUfrUlws89IiGQiscmvp8WamFnY3Z9HMzwSqV0Aj62SjPM811Iog+uRY2thH+wunVHDovj1NNI1bfGgmu1LEIivoRwnUKd3wyx7HurgQxt4hrN2AhOvCQsUms6NU/n/cGBbo1J2s=
  on:
    branch: master
