language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install LinkChecker
  - gem install jekyll
  - gem install jekyll-sitemap
  - gem install s3_website
  - gem install compass --version 0.12.5
  - gem install kramdown
  - gem install travis
before_script:
  - travis lint
  - python scripts/insert_demo.py
script:
  - nosetests --with-coverage --cover-package proselint
  - cd site
  - jekyll build
  - s3_website push
  - cd ..
  - linkchecker 'http://prose.lifelinter.com'
  - pep8 .
  - pep257 . --match='.*\.py'
after_success:
  - coveralls
env:
  global:
  - secure: cB2hODqR9V3P8c2BupySJnz825snT2vqhpB4RnnyYD5L1E+nzZK9KdApgx0U/f1YHZujhPnbdXAfq1QQztIf6EocbF1CrSKPCavJoJ/CSQ53X775++PegBZXL66PSYfMX28MFcuYCvqcBxSKX26kpT72IjtgHHEROz/NkrifHog=
  - secure: Ri3M0/J5J11LpMSSD3XoJdB/rkINP3Ir9leoUfrUlws89IiGQiscmvp8WamFnY3Z9HMzwSqV0Aj62SjPM811Iog+uRY2thH+wunVHDovj1NNI1bfGgmu1LEIivoRwnUKd3wyx7HurgQxt4hrN2AhOvCQsUms6NU/n/cGBbo1J2s=
  on:
    branch: master
deploy:
  provider: heroku
  api_key:
    secure: L3Z04s4YxouUA4pzDW38GusXQ82KNCI73RYUCpZhBXhtxqB3hK5dHX0/UMUnXWJLyu7fuZoYLfSAs2dIl2dNAvxN0OeRBSHR/hToprASfxBKiVfmzKJUE4UxzUkRbxxFcoA4pqSz6AcXQPW1NOVkvD7IMgKEqMJQyehonysw66k=
  app: proselint
  on:
    repo: amperser/proselint
notifications:
  email:
    recipients:
    - suchow@post.harvard.edu
    on_success: always
    on_failure: always
addons:
  code_climate:
    repo_token: 32f92d10b6a0f99a4b35f3e7022040f10dc68b640525237af401b7c4e44faf46
